<a href="https://colab.research.google.com/github/mahn-bonnie/Artificial-Intelligence/blob/master/Lab2b_Tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [22]:
#Task 1
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
sumArr=arr1+arr2
print(sumArr)
print(type(sumArr))

[ 6  8 10 12]
<class 'numpy.ndarray'>


In [23]:
#Task 2
import numpy as np
arr1=np.array([1,2,3,4])
mulArr=arr1*5
print(mulArr)

[ 5 10 15 20]


In [24]:
#Task 3
import numpy as np
arr1=np.array([1,2,3,4])
reArr=np.reshape(arr1,(2,2))
reArr

array([[1, 2],
       [3, 4]])

In [37]:
#Task 4
import numpy as np

arr1 = np.array([1, 2, 3, 4])
strArr = (arr1)
print(type(strArr))


<class 'numpy.ndarray'>


In [39]:
import numpy as np

arr = np.array([5, 10, 15, 20])
arr_str = (arr)
print(type(arr_str))
print("String Representation:", arr_str)


<class 'numpy.ndarray'>
String Representation: [ 5 10 15 20]


In [40]:
#Task 5
import numpy as np
arr=np.arange(0,101,2)
print(arr)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [41]:
#Task 6
import numpy as np
arr1=np.array([1,3,5,7,2,3])
arr2=np.array([2,3,5,7,2,4])
result=np.where(arr1==arr2)
print(result)

(array([1, 2, 3, 4]),)
